### ISSUE TITLE
Option localization

### ISSUE THREAD

**Issue by AlexTheGoat69** [Dorukyum/pycord-i18n#1]
Some commands have multiple arguments and have multiple descriptions per command how would this be handle.

async def remindme(ctx, time: Option(description="Format is as following: 100s, 1m, 1h, 1d"), reason: Option(description="Your reason for the reminder")):

**Comment by Dorukyum** [comment]
Support for option localization is the next thing I'm going to add.

**Comment by Dorukyum** [comment]
You can join the [support server](https://discord.gg/8JsMVhBP4W) to stay updated.

**Comment by Dorukyum** [comment]
I added support in https://github.com/Dorukyum/pycord-i18n/commit/5e8759a778cb7d0ece8578d256ad6296234ecda5 and released version `1.1.0` on PyPI, run `pip install -U pycord-i18n` to update the library.
