### ISSUE TITLE
Not available in pycord 2.5.0

### ISSUE THREAD

**Issue by ParrotXray** [Dorukyum/pycord-i18n#2]
An error occurred when using pycord 2.5.0
```
Traceback (most recent call last):
  File "C:\Users\Chino\Desktop\桜の夜\Bot\Bot.py", line 153, in <module>
    i18n.localize_commands()
  File "C:\Users\Chino\AppData\Local\Programs\Python\Python310\lib\site-packages\pycord\i18n\__init__.py", line 188, in localize_commands
    self._localize_command(
  File "C:\Users\Chino\AppData\Local\Programs\Python\Python310\lib\site-packages\pycord\i18n\__init__.py", line 142, in _localize_command
    command.name_localizations[locale] = name
TypeError: '_MissingSentinel' object does not support item assignment
```
![螢幕擷取畫面 2024-03-03 144528](https://github.com/Dorukyum/pycord-i18n/assets/87219725/f346f078-cea9-457d-9e32-63d927b6f49a)

**Comment by Dorukyum** [comment]
Will look into it.

**Comment by ParrotXray** [comment]
> Will look into it.

I have downloaded the code and made simple modifications, and it can now be executed normally.

**Comment by Dorukyum** [comment]
@ParrotXray Can you confirm that the changes I made in the latest commit (https://github.com/Dorukyum/pycord-i18n/commit/822ea22733e0f242f48e93e362038390dfa0443b) fix this issue?

**Comment by ParrotXray** [comment]
Normal operation after replacement

**Comment by ParrotXray** [comment]
@Dorukyum Normal operation after replacement

**Comment by Dorukyum** [comment]
`pycord-i18n v1.2.1` is now published on PyPI: https://pypi.org/project/pycord-i18n/1.2.1/
